POST http://localhost:4560/api/auth/register
Content-Type: application/json

{
    "name": "Md. Majedul Islam",
    "email": "majedul@gmail.com",
    "password": "Test123!" 
}


###
POST http://localhost:4560/api/auth/login
Content-Type: application/json

{
    "email": "majedul@gmail.com",
    "password": "Test123!"
}